services:
  web:
    build:
      context: .  # Root directory of your project
      dockerfile: Dockerfile
      target: dev  # Use the development target from the Dockerfile
    container_name: web
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached  # Mount the entire root directory
      - node_modules:/app/node_modules  # Persist node_modules between restarts
    command: >
      sh -c "
        npm run dev
      "
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  node_modules: